AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to deploy Docker container in ECS using EC2 instances and VPC, with HTTP support.

Parameters:
  CoachingLatestAmiId:
    Description: The latest AMI ID for ECS-optimized Amazon Linux 2.
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id

  CoachingExistingSecurityGroup:
    Description: The existing security group ID for the Load Balancer.
    Type: String
    Default: sg-0d07c53e841cccbd8
  
  CoachingDockerImageTag:
    Description: Docker image tag to deploy
    Type: String
    Default: 'latest'

Resources:
  CoachingVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  CoachingPublicSubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref CoachingVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true

  CoachingPublicSubnetTwo:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref CoachingVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true

  CoachingInternetGateway:
    Type: AWS::EC2::InternetGateway

  CoachingVPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref CoachingVPC
      InternetGatewayId: !Ref CoachingInternetGateway

  CoachingPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref CoachingVPC

  CoachingPublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref CoachingPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref CoachingInternetGateway

  CoachingSubnetRouteTableAssociationOne:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref CoachingPublicSubnetOne
      RouteTableId: !Ref CoachingPublicRouteTable

  CoachingSubnetRouteTableAssociationTwo:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref CoachingPublicSubnetTwo
      RouteTableId: !Ref CoachingPublicRouteTable

  CoachingECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: CoachingProcessorCluster

  CoachingEC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
       
  CoachingEC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: CoachingEC2InstanceRole

  CoachingECSInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH access to ECS instances
      VpcId: !Ref CoachingVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  CoachingEC2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: CoachingECSLaunchTemplate
      LaunchTemplateData:
        InstanceType: t2.micro
        ImageId: !Ref CoachingLatestAmiId
        IamInstanceProfile:
          Arn: !GetAtt CoachingEC2InstanceProfile.Arn
        SecurityGroupIds:
          - !Ref CoachingECSInstanceSecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            echo ECS_CLUSTER=${CoachingECSCluster} >> /etc/ecs/ecs.config
            echo ECS_ENABLE_TASK_IAM_ROLE=true >> /etc/ecs/ecs.config
            echo ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true >> /etc/ecs/ecs.config

  CoachingAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: 1
      MaxSize: 1
      DesiredCapacity: 1
      LaunchTemplate:
        LaunchTemplateId: !Ref CoachingEC2LaunchTemplate
        Version: !GetAtt CoachingEC2LaunchTemplate.LatestVersionNumber
      VPCZoneIdentifier:
        - !Ref CoachingPublicSubnetOne
        - !Ref CoachingPublicSubnetTwo

  CoachingLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Subnets:
        - !Ref CoachingPublicSubnetOne
        - !Ref CoachingPublicSubnetTwo
      SecurityGroups:
        - !Ref CoachingECSInstanceSecurityGroup

  CoachingECSTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId: !Ref CoachingVPC
      TargetType: ip
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: "/health"
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 2

  CoachingHTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - CoachingLoadBalancer
      - CoachingECSTargetGroup
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref CoachingECSTargetGroup
      LoadBalancerArn: !Ref CoachingLoadBalancer
      Port: 80
      Protocol: HTTP

  CoachingTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: coaching-processing-task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - EC2
      ContainerDefinitions:
        - Name: coaching-processing-container
          Image: !Ref CoachingDockerImageTag
          Essential: true
          PortMappings:
            - ContainerPort: 80
              HostPort: 80

  CoachingECSService:
    Type: AWS::ECS::Service
    DependsOn: CoachingHTTPListener
    Properties:
      Cluster: !Ref CoachingECSCluster
      DesiredCount: 1
      TaskDefinition: !Ref CoachingTaskDefinition
      LaunchType: EC2
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !Ref CoachingPublicSubnetOne
            - !Ref CoachingPublicSubnetTwo
      LoadBalancers:
        - ContainerName: coaching-processing-container
          ContainerPort: 80
          TargetGroupArn: !Ref CoachingECSTargetGroup