name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main  

env:
  IMAGE_TAG: ghcr.io/gamified-coaching-app/coaching_processor:v1.0
  IMAGE_TAGE_NAME: CoachingDockerImageTag
  CLUSTER_NAME: CoachingProcessorCluster
  STACK_NAME: CoachingProcessorStack
  LAMBDA_FUNCTION_NAME: coaching-processor-daily-trigger

jobs:
  unit_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  publish_docker_image:
    needs: unit_testing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write  # Required for GITHUB_TOKEN authentication

    steps:
    - uses: actions/checkout@v2
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: GabrielOppermann
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile  
        push: true
        tags: ${{ env.IMAGE_TAG }}
  
  deploy_stack:
    needs: publish_docker_image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2 

    - name: Deploy CloudFormation Stack
      run: |
        set -e
        aws cloudformation deploy \
          --template-file infrastructure/template.yaml \
          --stack-name ${{ env.STACK_NAME }} \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides ${{ env.IMAGE_TAGE_NAME }}=${{ env.IMAGE_TAG }} \
          --no-fail-on-empty-changeset \
          --region eu-west-2 \
          --debug
      
    - name: Check CloudFormation Outputs
      run: |
        aws cloudformation describe-stacks \
          --stack-name ${{ env.STACK_NAME }} \
          --query "Stacks[0].Outputs" \
          --output json

  deploy_container_on_ecs:
    needs: deploy_stack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2 
  
    - name: Get ECS Service Name
      id: get_ecs_service_name
      run: |
        ecs_service_name=$(aws ecs list-services \
          --cluster ${{ env.CLUSTER_NAME }} \
          --query "serviceArns[0]" \
          --output text)
        echo "ecs_service_name=${ecs_service_name##*/}" >> $GITHUB_ENV
    
    - name: Update ECS deployment
      run: |
        set -e
        aws ecs update-service \
          --cluster ${{ env.CLUSTER_NAME }} \
          --service ${{ env.ecs_service_name }} \
          --force-new-deployment
      shell: /usr/bin/bash -e {0}
      env:
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
        AWS_DEFAULT_REGION: eu-west-2
        AWS_REGION: eu-west-2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  
  deploy_daily_trigger_lambda:
    needs: deploy_container_on_ecs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: src/dailyLambdaTrigger
        run: npm install

      - name: Package Lambda function
        run: |
          cd src/dailyLambdaTrigger
          zip -r ../../lambda.zip . -x '*.git*'
          cd ../..
          zip -ur lambda.zip node_modules

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Get Lambda Function ARN
        id: get_lambda_arn
        run: |
          lambda_arn=$(aws lambda get-function --function-name ${{ env.LAMBDA_FUNCTION_NAME }} --query 'Configuration.FunctionArn' --output text)
          echo "lambda_arn=${lambda_arn}" >> $GITHUB_ENV

      - name: Deploy to AWS Lambda
        run: aws lambda update-function-code --function-name ${{ env.lambda_arn }} --zip-file fileb://lambda.zip